### ISSUE TITLE
.DS_Store files causing "lein droid doall" errors. 

### ISSUE THREAD

**Issue by benmathes** [krisc/events#6]
Not an issue with this tutorial, but something I found that i'd like to help fix if anyone else comes across this:

Some part of the complication is using the output from `ls` in the android sdk folders, and picking up OSX's `.DS_Store` files. For example, this error:

```
$ lein droid doall
Generating R.java...
The path /path/to/android/sdk/build-tools/.DS_Store/aapt doesn't exist. Abort execution.
```

just `rm` the offending .DS_Store files and you'll be all set.

**Comment by krisc** [comment]
Thanks for the tip! If you wanna open an issue at the lein-droid github, then maybe Alex will be able to fix this so Mac users wouldn't have to do this workaround. https://github.com/clojure-android/lein-droid/issues

**Comment by benmathes** [comment]
Good call. https://github.com/clojure-android/lein-droid/issues/80
